export { default as CustomerDetails } from "./CustomerDetails"
export { default as AllList } from "./AllList"
export { default as ClientList } from "./ClientList"
export { default as ProspectList } from "./ProspectList"
export { default as PolicyList } from "./PolicyList"
export { default as LostList } from "./LostList"
export { default as SearchAll } from "./SearchAll"
