export const data = [
    {
        id: "1",
        holderFirstName: "Rolando",
        holderLastName: "Yera",
        isProspect: false,
        source: "Website",
        holderEmail: "rolysemail@gmail.com",
        holderPhoneNumber: "(786) 277-2728",
        holderAddress: "902 West 79 Place",
    },
    {
        id: "2",
        holderFirstName: "Rolando",
        holderLastName: "Yera",
        isProspect: false,
        source: "Website",
        holderEmail: "rolysemail@gmail.com",
        holderPhoneNumber: "(786) 277-2728",
        holderAddress: "902 West 79 Place",
    },
    {
        id: "3",
        holderFirstName: "Rolando",
        holderLastName: "Yera",
        isProspect: false,
        source: "Website",
        holderEmail: "rolysemail@gmail.com",
        holderPhoneNumber: "(786) 277-2728",
        holderAddress: "902 West 79 Place",
    },
    {
        id: "4",
        holderFirstName: "Rolando",
        holderLastName: "Yera",
        isProspect: false,
        source: "Website",
        holderEmail: "rolysemail@gmail.com",
        holderPhoneNumber: "(786) 277-2728",
        holderAddress: "902 West 79 Place",
    },
    {
        id: "5",
        holderFirstName: "Rolando",
        holderLastName: "Yera",
        isProspect: false,
        source: "Website",
        holderEmail: "rolysemail@gmail.com",
        holderPhoneNumber: "(786) 277-2728",
        holderAddress: "902 West 79 Place",
    },
    {
        id: "6",
        holderFirstName: "Rolando",
        holderLastName: "Yera",
        isProspect: false,
        source: "Website",
        holderEmail: "rolysemail@gmail.com",
        holderPhoneNumber: "(786) 277-2728",
        holderAddress: "902 West 79 Place",
    },
    {
        id: "7",
        holderFirstName: "Rolando",
        holderLastName: "Yera",
        isProspect: false,
        source: "Website",
        holderEmail: "rolysemail@gmail.com",
        holderPhoneNumber: "(786) 277-2728",
        holderAddress: "902 West 79 Place",
    },
    {
        id: "8",
        holderFirstName: "Rolando",
        holderLastName: "Yera",
        isProspect: false,
        source: "Website",
        holderEmail: "rolysemail@gmail.com",
        holderPhoneNumber: "(786) 277-2728",
        holderAddress: "902 West 79 Place",
    },
    {
        id: "9",
        holderFirstName: "Rolando",
        holderLastName: "Yera",
        isProspect: false,
        source: "Website",
        holderEmail: "rolysemail@gmail.com",
        holderPhoneNumber: "(786) 277-2728",
        holderAddress: "902 West 79 Place",
    },
    {
        id: "10",
        holderFirstName: "Rolando",
        holderLastName: "Yera",
        isProspect: false,
        source: "Website",
        holderEmail: "rolysemail@gmail.com",
        holderPhoneNumber: "(786) 277-2728",
        holderAddress: "902 West 79 Place",
    },
    {
        id: "11",
        holderFirstName: "Rolando",
        holderLastName: "Yera",
        isProspect: false,
        source: "Website",
        holderEmail: "rolysemail@gmail.com",
        holderPhoneNumber: "(786) 277-2728",
        holderAddress: "902 West 79 Place",
    },
    {
        id: "12",
        holderFirstName: "Rolando",
        holderLastName: "Yera",
        isProspect: false,
        source: "Website",
        holderEmail: "rolysemail@gmail.com",
        holderPhoneNumber: "(786) 277-2728",
        holderAddress: "902 West 79 Place",
    },
    {
        id: "13",
        holderFirstName: "Rolando",
        holderLastName: "Yera",
        isProspect: false,
        source: "Website",
        holderEmail: "rolysemail@gmail.com",
        holderPhoneNumber: "(786) 277-2728",
        holderAddress: "902 West 79 Place",
    },
    {
        id: "14",
        holderFirstName: "Rolando",
        holderLastName: "Yera",
        isProspect: false,
        source: "Website",
        holderEmail: "rolysemail@gmail.com",
        holderPhoneNumber: "(786) 277-2728",
        holderAddress: "902 West 79 Place",
    },
    {
        id: "15",
        holderFirstName: "Rolando",
        holderLastName: "Yera",
        isProspect: false,
        source: "Website",
        holderEmail: "rolysemail@gmail.com",
        holderPhoneNumber: "(786) 277-2728",
        holderAddress: "902 West 79 Place",
    },
    {
        id: "16",
        holderFirstName: "Rolando",
        holderLastName: "Yera",
        isProspect: false,
        source: "Website",
        holderEmail: "rolysemail@gmail.com",
        holderPhoneNumber: "(786) 277-2728",
        holderAddress: "902 West 79 Place",
    },
]
